services:
  mariadb:
    image: mariadb:11.2.6@sha256:ff87d49107a1e4878c63c3a3132bfdf628e6732879b8e4ceb72e041206d3aece
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:12.0.2@sha256:b945125607081d1a239133d650741906dc7ac63f66bf12208e175fd9e2fc5e1f
    command: migrate
    depends_on:
      mariadb:
        condition: service_healthy

  spring-webflux-aggregator:
    depends_on:
      mariadb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          "CMD",
          "busybox",
          "wget",
          "-q",
          "-O",
          "/dev/null",
          "http://localhost:8080/health/ping",
        ]
      interval: 5s
      timeout: 5s
      retries: 60

  spring-telegram-webhook:
    depends_on:
      mariadb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
      spring-webflux-aggregator:
        condition: service_healthy

  ngrok:
    image: ngrok/ngrok:3@sha256:07bd8fa758e73489d3ba5a2fc95d912e0b8359ebfca4a55886e2059c10020da4
    command: http host.docker.internal:5050

  mock-server:
    image: mockserver/mockserver:5.15.0@sha256:0f9ef78c94894ac3e70135d156193b25e23872575d58e2228344964273b4af6b
    profiles: ["mock"]
    command: >
      -logLevel DEBUG 
      -serverPort 1080

volumes:
  mariadb_data:
