services:
  mariadb:
    image: mariadb:11.2.6@sha256:ff87d49107a1e4878c63c3a3132bfdf628e6732879b8e4ceb72e041206d3aece
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:11.17.1@sha256:bc77a3e20cd43dd5bfe108e35f924e514ac06ce2f2887d3df3379d4aa66e2c8d
    command: migrate
    depends_on:
      mariadb:
        condition: service_healthy

  spring-webflux-aggregator:
    depends_on:
      mariadb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          "CMD",
          "busybox",
          "wget",
          "-q",
          "-O",
          "/dev/null",
          "http://localhost:8080/health/ping",
        ]
      interval: 5s
      timeout: 5s
      retries: 60

  spring-telegram-webhook:
    depends_on:
      mariadb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
      spring-webflux-aggregator:
        condition: service_healthy

  ngrok:
    image: ngrok/ngrok:3@sha256:168300d4dbdb6fede89eaeb188db72efcab73dd408bd358301e9ee0bb8a41a51
    command: http host.docker.internal:5050

  mock-server:
    image: mockserver/mockserver:5.15.0@sha256:0f9ef78c94894ac3e70135d156193b25e23872575d58e2228344964273b4af6b
    command: >
      -logLevel DEBUG 
      -serverPort 1080

volumes:
  mariadb_data:
